name: Workflow

on: [pull_request]

jobs:
  EventJSON:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ls -Ral
      run: ls -Ral
    - name: $GITHUB_EVENT_PATH
      run: cat $GITHUB_EVENT_PATH
    - name: From
      run: echo ${{ github.base_ref }}
    - name: To
      run: echo ${{ github.head_ref }}     
    - name: Diff
      run: git diff origin/${{ github.head_ref }} > diff.txt
    - name: Cat
      run: cat diff.txt
    - name: ls -Ral
      run: ls -Ral      
