name: Workflow

on: [pull_request]

jobs:
  EventJSON:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: ls -Ral
      run: name ls -Ral
    - name: workflow/event.json
      run: cat workflow/event.json
